name: openclaw
icon: openclaw
type: service
title: OpenClaw
hostname: openclaw
containers:
  - name: openclaw
    image: wodby/openclaw
options:
  - version: '2026'
    tag: '2026'
labels:
  - openclaw

endpoints:
- name: openclaw
  ports:
  - name: openclaw
    number: 18789
    protocol: http
    private: true
    main: true

env:
- name: OPENCLAW_GATEWAY_CONTROLUI_ALLOWED_ORIGIN
  value: 'http://{{service.host}}.{{instance.namespace}}.svc.cluster.local:{{service.mainPort.number}}'

tokens:
  - name: gateway_token
    generate:
      regex: '[0-9a-z-]{32}'

volumes:
- name: data
  title: Data
  size: 1
  optional: false
  helm: 
    labels: persistence.labels    
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'
    # mandatory to use existing claim since this volume will have import function
    # we will mount different claim after import and doing it through sts's volumeclaimtemplates is not supported
# disabled due to missing imports (required for this to work – we create PVC manually instead of using volumeClaimTemplate)
#    - name: primary.persistence.existingClaim
#      value: '{{volumes.spool.claim}}'

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/openclaw
  chart: oci://registry-1.docker.io/wodby/openclaw
  version: 0.1.0
  configurations:
    - name: openclaw
      labels: podLabels
      annotations: podAnnotations
      env: envVars
      resources: resources
      volumes: volumes
      mounts: volumeMounts
  values:
    - name: gatewayToken
      value: '{{gateway_token}}'

